#simple linear regresion
- This is an ml algorithm that is used to train the model.
- There will be one independent column and 1dependent column.
- We should consider the independent column as X and dependent column as y.
- Just assign the columns to the x and y variables.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#here age column and salary column are there in our data .
df=pd.DataFrame({'Age': np.random.randint(18, 60, 10),
    'Salary': np.random.randint(200, 80000, 10)})
df

   Age  Salary
0   25   28318
1   27   54624
2   26   31882
3   45   49394
4   45   77607
5   47   10313
6   51   47957
7   36   78554
8   23   54940
9   42   13466

In [7]:
#age is independent column and salary is dependent column
X=df[['Age']]
X.ndim #independent column should be in 2d array
y=df['Salary']
print(X)
print('--------------------------------------')
print(y)

   Age
0   25
1   27
2   26
3   45
4   45
5   47
6   51
7   36
8   23
9   42
--------------------------------------
0    28318
1    54624
2    31882
3    49394
4    77607
5    10313
6    47957
7    78554
8    54940
9    13466
Name: Salary, dtype: int64

- Once data is sepearated in dependend and independed then we should split the data according to our test and training size by giving that to the train test split function.
- We should import the module form the model selection that is in the sklearn.

In [9]:
import sklearn
from sklearn.model_selection import train_test_split

- When we give the data to the train test split then it will give us four outputs.
- X_train,X_test,y_train,y_test this are thee values that need to be stored in the varialbes

- We give the variables that are created at the starting X and y.

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
#we use test size for the data seperation for training and testing of the data.
# test size should be blw 0 and 1 for the correct seperation ,if we use integer values then that no. of values will be goes to the testing .

In [13]:
#now we should create the testing and training data sheets seperately.
#training data excel.
training_data=pd.DataFrame({'X_train':np.ravel(X_train),'y_train':y_train})
training_data

   X_train  y_train
0       25    28318
7       36    78554
2       26    31882
9       42    13466
4       45    77607
3       45    49394
6       51    47957

- When we give the X values that are in the 2d array but we should give that to the numpy and make that to 1d arary .
- y values are already in 1d so need to change that.

In [15]:
#testing data excel
Testing_data=pd.DataFrame({'X_test':np.ravel(X_test),'y_test':y_test})
Testing_data

   X_test  y_test
8      23   54940
1      27   54624
5      47   10313

In [20]:
#training and testing data
print(len(X_train),len(y_train))#training
print(len(X_test),len(y_test)) #testing

7 7
3 3

- Now we train our data
- In simple linear regresion we train the data using the maths that is a straight line equation from that the data is trained and becomes the model.
- For training the data we give the data to the linear regression class in that there will be fit and predict fn that are used to train and test.

In [22]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression() #here we give our alogirthm to the object

In [23]:
reg.fit(X_train,y_train) #our algorithm is trained and the model is ready .

LinearRegression()